name: Build and Deploy Unity WebGL

on:
  push:
    branches:
      
      - master  # 또는 - main

jobs:
  build:
    name: Build WebGL
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v3

      
      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-WebGL-${{ hashFiles('*/.cs') }}
          restore-keys: |
            Library-WebGL-

      
      - name: Set up Unity
        uses: game-ci/unity-actions/setup@v2
        with:
          unityVersion: 2022.3.18f1

      
      - name: Build WebGL
        uses: game-ci/unity-actions/build@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL

      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/WebGL/WebGL